# VERSION
version: '1.0.0'

simulation:
  diffusion_constant: 0.02
  pyfr_backend: metal
  pyfr_case: tests/cfd/pyfr-backend/test-flows/2d-double-mach-reflection
  # The following directory- and trajectory-related settings are experiment-specific
  # and have been moved into individual experiment YAMLs. Defaults will still be
  # provided by the code when missing.